ALTER TABLE TOPIC DROP FOREIGN KEY FK_TOPIC_TOPICTYPE_ID
ALTER TABLE USER DROP FOREIGN KEY FK_USER_TEACHER
ALTER TABLE DOCUMENT_COMMENT DROP FOREIGN KEY FK_DOCUMENT_COMMENT_PARENT_DOCUMENT
ALTER TABLE DOCUMENT_COMMENT DROP FOREIGN KEY FK_DOCUMENT_COMMENT_USER
ALTER TABLE ATTACHMENT DROP FOREIGN KEY FK_ATTACHMENT_CREATOR
ALTER TABLE ATTACHMENT DROP FOREIGN KEY FK_ATTACHMENT_DOCUMENT
ALTER TABLE DOCUMENT DROP FOREIGN KEY FK_DOCUMENT_CREATOR
ALTER TABLE DOCUMENT DROP FOREIGN KEY FK_DOCUMENT_LAST_MODIFIED_BY
DROP TABLE TOPIC
DROP TABLE TOPIC_TYPE
DROP TABLE USER
DROP TABLE MENU
DROP TABLE WILL
DROP TABLE TIME_NODE
DROP TABLE DOCUMENT_COMMENT
DROP TABLE ATTACHMENT
DROP TABLE DOCUMENT
