ALTER TABLE TOPIC DROP FOREIGN KEY FK_TOPIC_STUDENT
ALTER TABLE USER DROP FOREIGN KEY FK_USER_TEACHER
ALTER TABLE WILL DROP FOREIGN KEY FK_WILL_TEACHER_ID
ALTER TABLE WILL DROP FOREIGN KEY FK_WILL_STUDENT_ID
ALTER TABLE DOCUMENT_COMMENT DROP FOREIGN KEY FK_DOCUMENT_COMMENT_PARENT_DOCUMENT
ALTER TABLE DOCUMENT_COMMENT DROP FOREIGN KEY FK_DOCUMENT_COMMENT_USER
ALTER TABLE ATTACHMENT DROP FOREIGN KEY FK_ATTACHMENT_CREATOR
ALTER TABLE ATTACHMENT DROP FOREIGN KEY FK_ATTACHMENT_DOCUMENT
ALTER TABLE ATTACHMENT DROP FOREIGN KEY FK_ATTACHMENT_SYSTEM_MESSAGE
ALTER TABLE DOCUMENT DROP FOREIGN KEY FK_DOCUMENT_CREATOR
ALTER TABLE DOCUMENT DROP FOREIGN KEY FK_DOCUMENT_LAST_MODIFIED_BY
ALTER TABLE ACTION_EVENT DROP FOREIGN KEY FK_ACTION_EVENT_ACTOR
ALTER TABLE ACTION_EVENT DROP FOREIGN KEY FK_ACTION_EVENT_LISTENER
ALTER TABLE TIMENODE_ACCESSRULE DROP FOREIGN KEY FK_TIMENODE_ACCESSRULE_TIME_NODE_ID
ALTER TABLE TIMENODE_ACCESSRULE DROP FOREIGN KEY FK_TIMENODE_ACCESSRULE_ACCESS_RULE_ID
DROP TABLE TOPIC
DROP TABLE USER
DROP TABLE MENU
DROP TABLE WILL
DROP TABLE TIME_NODE
DROP TABLE DOCUMENT_COMMENT
DROP TABLE ATTACHMENT
DROP TABLE DOCUMENT
DROP TABLE ACTION_EVENT
DROP TABLE SYSTEM_MESSAGE
DROP TABLE ACCESS_RULE
DROP TABLE TIMENODE_ACCESSRULE
